stages:
  data_ingestion:
    cmd: python src/preprocessing/data_ingestion.py
    deps:
    - src/preprocessing/data_ingestion.py
    params:
    - data_ingestion.test_size
    outs:
    - data/raw
  data_preprocessing:
    cmd: python src/preprocessing/data_preprocessing.py
    deps:
    - data/raw
    - src/preprocessing/data_preprocessing.py
    outs:
    - data/processed
  feature_engineering:
    cmd: python src/features/feature_engineering.py
    deps:
    - data/processed
    - src/features/feature_engineering.py
    params:
    - feature_engineering.max_features
    outs:
    - data/features
  model_building:
    cmd: python src/models/model_building.py
    deps:
    - data/features
    - src/models/model_building.py
    params:
    - model_building.eta
    - model_building.gamma
    outs:
    - models/model.pkl
  model_evaluation:
    cmd: python src/models/model_evaluation.py
    deps:
    - models/model.pkl
    - src/models/model_evaluation.py
    metrics:
    - metrics.json


